project:
  type: website
  output-dir: docs
  
website:
  title: "Penn GSE"
  favicon: simplified-shield-final-60.png
  back-to-top-navigation: true
  page-footer:
    left: |
      Made with [![Quarto](https://quarto.org/quarto.png){width=65}](https://quarto.org/){target="_blank"}
    right:
      - icon: github
        href: https://github.com/baker-jr-john/Website
        target: _blank
    background: light

format:
  html:
    page-layout: full
    date-format: long
    sidebar: false
    navbar: false
    theme:
      light: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    toc: true
    link-external-newwindow: true