project:
  type: website
  output-dir: docs
  title: "Penn GSE"
  
website:
  search: false
  back-to-top-navigation: true
  
  repo-url: "https://github.com/baker-jr-john/Website.git"
  repo-actions: none

  page-footer: 
    border: true
    left: Made with [![Quarto](https://quarto.org/quarto.png){width=65}](https://quarto.org/){target="_blank"} 

format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    link-external-newwindow: true

editor: source
